import type { ItemDef } from '../types';

export const CONSTRUCTION_ITEMS: Record<string, ItemDef> = {
  // --- Raw materials (gathering node drops) ---
  rough_stone: {
    id: 'rough_stone',
    name: 'Rough Stone',
    kind: 'junk',
    quality: 'poor',
    sellValue: 2,
  },
  clay_lump: {
    id: 'clay_lump',
    name: 'Lump of Clay',
    kind: 'junk',
    quality: 'poor',
    sellValue: 2,
  },
  raw_lumber: {
    id: 'raw_lumber',
    name: 'Raw Lumber',
    kind: 'junk',
    quality: 'poor',
    sellValue: 3,
  },
  iron_ore_chunk: {
    id: 'iron_ore_chunk',
    name: 'Iron Ore Chunk',
    kind: 'junk',
    quality: 'common',
    sellValue: 5,
  },
  limestone_chunk: {
    id: 'limestone_chunk',
    name: 'Limestone Chunk',
    kind: 'junk',
    quality: 'poor',
    sellValue: 2,
  },
  sand_bag: {
    id: 'sand_bag',
    name: 'Bag of Sand',
    kind: 'junk',
    quality: 'common',
    sellValue: 4,
  },

  // --- Refined materials ---
  cut_stone: {
    id: 'cut_stone',
    name: 'Cut Stone',
    kind: 'junk',
    quality: 'common',
    sellValue: 8,
  },
  fired_brick: {
    id: 'fired_brick',
    name: 'Fired Brick',
    kind: 'junk',
    quality: 'common',
    sellValue: 10,
  },
  sawed_plank: {
    id: 'sawed_plank',
    name: 'Sawed Wooden Plank',
    kind: 'junk',
    quality: 'common',
    sellValue: 6,
  },
  iron_nail: {
    id: 'iron_nail',
    name: 'Iron Nail',
    kind: 'junk',
    quality: 'common',
    stackSize: 50,
    sellValue: 4,
  },
  clay_tile: {
    id: 'clay_tile',
    name: 'Clay Roof Tile',
    kind: 'junk',
    quality: 'common',
    sellValue: 10,
  },
  glass_pane: {
    id: 'glass_pane',
    name: 'Glass Pane',
    kind: 'junk',
    quality: 'uncommon',
    sellValue: 25,
  },
  limestone_mortar: {
    id: 'limestone_mortar',
    name: 'Limestone Mortar',
    kind: 'junk',
    quality: 'common',
    sellValue: 5,
  },
  marble_block: {
    id: 'marble_block',
    name: 'Marble Block',
    kind: 'junk',
    quality: 'rare',
    sellValue: 100,
  },
  enchanted_lumber: {
    id: 'enchanted_lumber',
    name: 'Enchanted Lumber',
    kind: 'junk',
    quality: 'epic',
    sellValue: 500,
  },

  // --- Canvas and fittings ---
  canvas_scrap: {
    id: 'canvas_scrap',
    name: 'Canvas Scrap',
    kind: 'junk',
    quality: 'poor',
    sellValue: 1,
    stackSize: 50,
  },
  // --- Special materials (higher tiers) ---
  iron_hinge: {
    id: 'iron_hinge',
    name: 'Iron Hinge',
    kind: 'junk',
    quality: 'common',
    sellValue: 12,
  },
  iron_grille: {
    id: 'iron_grille',
    name: 'Iron Grille',
    kind: 'junk',
    quality: 'uncommon',
    sellValue: 30,
  },
  reinforced_beam: {
    id: 'reinforced_beam',
    name: 'Reinforced Wooden Beam',
    kind: 'junk',
    quality: 'uncommon',
    sellValue: 40,
  },
  granite_block: {
    id: 'granite_block',
    name: 'Granite Block',
    kind: 'junk',
    quality: 'uncommon',
    sellValue: 35,
  },
  crystal_pane: {
    id: 'crystal_pane',
    name: 'Crystal Window Pane',
    kind: 'junk',
    quality: 'epic',
    sellValue: 300,
  },
  rune_carved_stone: {
    id: 'rune_carved_stone',
    name: 'Rune-Carved Stone',
    kind: 'junk',
    quality: 'legendary',
    sellValue: 1200,
  },

  // --- Construction hand tools (tier 1-5) ---
  trowel_t1: {
    id: 'trowel_t1',
    name: "Builder's Trowel",
    kind: 'tool',
    quality: 'common',
    sellValue: 10,
    buyValue: 50,
    use: { type: 'gatherTool', professionId: 'construction', tier: 1 },
  },
  carpenter_hammer_t2: {
    id: 'carpenter_hammer_t2',
    name: "Carpenter's Hammer",
    kind: 'tool',
    quality: 'common',
    sellValue: 25,
    buyValue: 125,
    use: { type: 'gatherTool', professionId: 'construction', tier: 2 },
  },
  frame_saw_t3: {
    id: 'frame_saw_t3',
    name: 'Frame Saw',
    kind: 'tool',
    quality: 'uncommon',
    sellValue: 60,
    buyValue: 300,
    use: { type: 'gatherTool', professionId: 'construction', tier: 3 },
  },
  builder_level_t4: {
    id: 'builder_level_t4',
    name: "Builder's Level",
    kind: 'tool',
    quality: 'rare',
    sellValue: 150,
    buyValue: 750,
    use: { type: 'gatherTool', professionId: 'construction', tier: 4 },
  },
  master_mallet_t5: {
    id: 'master_mallet_t5',
    name: "Master Builder's Mallet",
    kind: 'tool',
    quality: 'epic',
    sellValue: 400,
    buyValue: 2000,
    use: { type: 'gatherTool', professionId: 'construction', tier: 5 },
  },

  // --- Blueprint detail items (doors, windows, fittings) ---
  bedroll: {
    id: 'bedroll',
    name: 'Bedroll',
    kind: 'junk',
    quality: 'common',
    sellValue: 5,
  },
  candle: {
    id: 'candle',
    name: 'Candle',
    kind: 'junk',
    quality: 'common',
    sellValue: 2,
  },
  door_wooden: {
    id: 'door_wooden',
    name: 'Wooden Door',
    kind: 'junk',
    quality: 'common',
    sellValue: 15,
  },
  window_shutter: {
    id: 'window_shutter',
    name: 'Wooden Window Shutter',
    kind: 'junk',
    quality: 'common',
    sellValue: 10,
  },
  door_sturdy: {
    id: 'door_sturdy',
    name: 'Sturdy Wooden Door',
    kind: 'junk',
    quality: 'uncommon',
    sellValue: 40,
  },
  door_ironbound: {
    id: 'door_ironbound',
    name: 'Ironbound Door',
    kind: 'junk',
    quality: 'rare',
    sellValue: 120,
  },
  door_runic: {
    id: 'door_runic',
    name: 'Runic Door',
    kind: 'junk',
    quality: 'epic',
    sellValue: 500,
  },

  // --- Blueprint scroll items (consumable, learned) ---
  blueprint_tent: {
    id: 'blueprint_tent',
    name: 'Blueprint: Tent',
    kind: 'quest',
    quality: 'common',
    sellValue: 1,
    noDiscard: true,
  },
  blueprint_wooden_shack: {
    id: 'blueprint_wooden_shack',
    name: 'Blueprint: Wooden Shack',
    kind: 'quest',
    quality: 'common',
    sellValue: 10,
    buyValue: 100,
    noDiscard: true,
  },
  blueprint_timber_cottage: {
    id: 'blueprint_timber_cottage',
    name: 'Blueprint: Timber Cottage',
    kind: 'quest',
    quality: 'uncommon',
    sellValue: 50,
    buyValue: 500,
    noDiscard: true,
  },
  blueprint_stone_house: {
    id: 'blueprint_stone_house',
    name: 'Blueprint: Stone House',
    kind: 'quest',
    quality: 'rare',
    sellValue: 200,
    buyValue: 2000,
    noDiscard: true,
  },
  blueprint_manor: {
    id: 'blueprint_manor',
    name: 'Blueprint: Country Manor',
    kind: 'quest',
    quality: 'epic',
    sellValue: 800,
    buyValue: 8000,
    noDiscard: true,
  },
  blueprint_grand_estate: {
    id: 'blueprint_grand_estate',
    name: 'Blueprint: Grand Estate',
    kind: 'quest',
    quality: 'legendary',
    sellValue: 2500,
    buyValue: 25000,
    noDiscard: true,
  },

  // --- Furniture items (Phase 5) ---
  rustic_chair: {
    id: 'rustic_chair',
    name: 'Rustic Chair',
    kind: 'junk',
    quality: 'poor',
    sellValue: 5,
  },
  rustic_table: {
    id: 'rustic_table',
    name: 'Rustic Table',
    kind: 'junk',
    quality: 'poor',
    sellValue: 8,
  },
  rustic_bed: {
    id: 'rustic_bed',
    name: 'Rustic Bed',
    kind: 'junk',
    quality: 'poor',
    sellValue: 12,
  },
  rustic_shelf: {
    id: 'rustic_shelf',
    name: 'Rustic Shelf',
    kind: 'junk',
    quality: 'poor',
    sellValue: 6,
  },
  rustic_rug: {
    id: 'rustic_rug',
    name: 'Rustic Rug',
    kind: 'junk',
    quality: 'poor',
    sellValue: 4,
  },
  rustic_lamp: {
    id: 'rustic_lamp',
    name: 'Rustic Lamp',
    kind: 'junk',
    quality: 'poor',
    sellValue: 7,
  },
  rustic_cabinet: {
    id: 'rustic_cabinet',
    name: 'Rustic Cabinet',
    kind: 'junk',
    quality: 'poor',
    sellValue: 15,
  },
  sturdy_chair: {
    id: 'sturdy_chair',
    name: 'Sturdy Chair',
    kind: 'junk',
    quality: 'common',
    sellValue: 20,
  },
  sturdy_table: {
    id: 'sturdy_table',
    name: 'Sturdy Table',
    kind: 'junk',
    quality: 'common',
    sellValue: 30,
  },
  sturdy_bed: {
    id: 'sturdy_bed',
    name: 'Sturdy Bed',
    kind: 'junk',
    quality: 'common',
    sellValue: 45,
  },
  sturdy_shelf: {
    id: 'sturdy_shelf',
    name: 'Sturdy Shelf',
    kind: 'junk',
    quality: 'common',
    sellValue: 25,
  },
  sturdy_rug: {
    id: 'sturdy_rug',
    name: 'Sturdy Rug',
    kind: 'junk',
    quality: 'common',
    sellValue: 15,
  },
  sturdy_lamp: {
    id: 'sturdy_lamp',
    name: 'Sturdy Lamp',
    kind: 'junk',
    quality: 'common',
    sellValue: 28,
  },
  ornate_chair: {
    id: 'ornate_chair',
    name: 'Ornate Chair',
    kind: 'junk',
    quality: 'uncommon',
    sellValue: 60,
  },
  ornate_table: {
    id: 'ornate_table',
    name: 'Ornate Table',
    kind: 'junk',
    quality: 'uncommon',
    sellValue: 80,
  },
  ornate_bed: {
    id: 'ornate_bed',
    name: 'Ornate Bed',
    kind: 'junk',
    quality: 'uncommon',
    sellValue: 120,
  },
  ornate_cabinet: {
    id: 'ornate_cabinet',
    name: 'Ornate Cabinet',
    kind: 'junk',
    quality: 'uncommon',
    sellValue: 90,
  },
  ornate_lamp: {
    id: 'ornate_lamp',
    name: 'Ornate Lamp',
    kind: 'junk',
    quality: 'uncommon',
    sellValue: 70,
  },
  ornate_rug: {
    id: 'ornate_rug',
    name: 'Ornate Rug',
    kind: 'junk',
    quality: 'uncommon',
    sellValue: 50,
  },
  exquisite_chair: {
    id: 'exquisite_chair',
    name: 'Exquisite Chair',
    kind: 'junk',
    quality: 'rare',
    sellValue: 200,
  },
  exquisite_table: {
    id: 'exquisite_table',
    name: 'Exquisite Table',
    kind: 'junk',
    quality: 'rare',
    sellValue: 250,
  },
  exquisite_bed: {
    id: 'exquisite_bed',
    name: 'Exquisite Bed',
    kind: 'junk',
    quality: 'rare',
    sellValue: 350,
  },
  exquisite_lamp: {
    id: 'exquisite_lamp',
    name: 'Exquisite Lamp',
    kind: 'junk',
    quality: 'rare',
    sellValue: 180,
  },
  masterwork_chair: {
    id: 'masterwork_chair',
    name: "Masterwork Chair",
    kind: 'junk',
    quality: 'epic',
    sellValue: 500,
  },
  masterwork_table: {
    id: 'masterwork_table',
    name: "Masterwork Table",
    kind: 'junk',
    quality: 'epic',
    sellValue: 600,
  },
  masterwork_bed: {
    id: 'masterwork_bed',
    name: "Masterwork Bed",
    kind: 'junk',
    quality: 'epic',
    sellValue: 800,
  },
  masterwork_rug: {
    id: 'masterwork_rug',
    name: "Masterwork Rug",
    kind: 'junk',
    quality: 'epic',
    sellValue: 400,
  },

  // --- Crafting station furniture items (Phase 6) ---
  station_workbench: {
    id: 'station_workbench',
    name: "Workbench",
    kind: 'junk',
    quality: 'common',
    sellValue: 50,
  },
  station_anvil: {
    id: 'station_anvil',
    name: "Anvil",
    kind: 'junk',
    quality: 'common',
    sellValue: 60,
  },
  station_alchemy: {
    id: 'station_alchemy',
    name: "Alchemy Station",
    kind: 'junk',
    quality: 'uncommon',
    sellValue: 120,
  },
  station_cooking_fire: {
    id: 'station_cooking_fire',
    name: "Cooking Fire",
    kind: 'junk',
    quality: 'common',
    sellValue: 40,
  },
  station_loom: {
    id: 'station_loom',
    name: "Loom",
    kind: 'junk',
    quality: 'common',
    sellValue: 45,
  },

  // --- Storage chest furniture items (Phase 6) ---
  chest_small: {
    id: 'chest_small',
    name: "Small Chest",
    kind: 'junk',
    quality: 'common',
    sellValue: 30,
  },
  chest_medium: {
    id: 'chest_medium',
    name: "Medium Chest",
    kind: 'junk',
    quality: 'uncommon',
    sellValue: 80,
  },
  chest_large: {
    id: 'chest_large',
    name: "Large Chest",
    kind: 'junk',
    quality: 'rare',
    sellValue: 200,
  },
  // Quest interact item: plot deed (sparkle object near builder_kael).
  plot_deed: {
    id: 'plot_deed',
    name: 'Building Plot Deed',
    kind: 'quest',
    quality: 'common',
    sellValue: 0,
    noDiscard: true,
  },
};
