import type { ItemDef } from '../types';

export const CONSTRUCTION_ITEMS: Record<string, ItemDef> = {
  // --- Raw materials (gathering node drops) ---
  rough_stone: {
    id: 'rough_stone',
    name: 'Rough Stone',
    kind: 'junk',
    quality: 'poor',
    sellValue: 2,
  },
  clay_lump: {
    id: 'clay_lump',
    name: 'Lump of Clay',
    kind: 'junk',
    quality: 'poor',
    sellValue: 2,
  },
  raw_lumber: {
    id: 'raw_lumber',
    name: 'Raw Lumber',
    kind: 'junk',
    quality: 'poor',
    sellValue: 3,
  },
  iron_ore_chunk: {
    id: 'iron_ore_chunk',
    name: 'Iron Ore Chunk',
    kind: 'junk',
    quality: 'common',
    sellValue: 5,
  },
  limestone_chunk: {
    id: 'limestone_chunk',
    name: 'Limestone Chunk',
    kind: 'junk',
    quality: 'poor',
    sellValue: 2,
  },
  sand_bag: {
    id: 'sand_bag',
    name: 'Bag of Sand',
    kind: 'junk',
    quality: 'common',
    sellValue: 4,
  },

  // --- Refined materials ---
  cut_stone: {
    id: 'cut_stone',
    name: 'Cut Stone',
    kind: 'junk',
    quality: 'common',
    sellValue: 8,
  },
  fired_brick: {
    id: 'fired_brick',
    name: 'Fired Brick',
    kind: 'junk',
    quality: 'common',
    sellValue: 10,
  },
  sawed_plank: {
    id: 'sawed_plank',
    name: 'Sawed Wooden Plank',
    kind: 'junk',
    quality: 'common',
    sellValue: 6,
  },
  iron_nail: {
    id: 'iron_nail',
    name: 'Iron Nail',
    kind: 'junk',
    quality: 'common',
    stackSize: 50,
    sellValue: 4,
  },
  clay_tile: {
    id: 'clay_tile',
    name: 'Clay Roof Tile',
    kind: 'junk',
    quality: 'common',
    sellValue: 10,
  },
  glass_pane: {
    id: 'glass_pane',
    name: 'Glass Pane',
    kind: 'junk',
    quality: 'uncommon',
    sellValue: 25,
  },
  limestone_mortar: {
    id: 'limestone_mortar',
    name: 'Limestone Mortar',
    kind: 'junk',
    quality: 'common',
    sellValue: 5,
  },
  marble_block: {
    id: 'marble_block',
    name: 'Marble Block',
    kind: 'junk',
    quality: 'rare',
    sellValue: 100,
  },
  enchanted_lumber: {
    id: 'enchanted_lumber',
    name: 'Enchanted Lumber',
    kind: 'junk',
    quality: 'epic',
    sellValue: 500,
  },

  // --- Special materials (higher tiers) ---
  iron_hinge: {
    id: 'iron_hinge',
    name: 'Iron Hinge',
    kind: 'junk',
    quality: 'common',
    sellValue: 12,
  },
  reinforced_beam: {
    id: 'reinforced_beam',
    name: 'Reinforced Wooden Beam',
    kind: 'junk',
    quality: 'uncommon',
    sellValue: 40,
  },
  granite_block: {
    id: 'granite_block',
    name: 'Granite Block',
    kind: 'junk',
    quality: 'uncommon',
    sellValue: 35,
  },
  crystal_pane: {
    id: 'crystal_pane',
    name: 'Crystal Window Pane',
    kind: 'junk',
    quality: 'epic',
    sellValue: 300,
  },
  rune_carved_stone: {
    id: 'rune_carved_stone',
    name: 'Rune-Carved Stone',
    kind: 'junk',
    quality: 'legendary',
    sellValue: 1200,
  },

  // --- Construction hand tools (tier 1-5) ---
  trowel_t1: {
    id: 'trowel_t1',
    name: "Builder's Trowel",
    kind: 'tool',
    quality: 'common',
    sellValue: 10,
    buyValue: 50,
  },
  carpenter_hammer_t2: {
    id: 'carpenter_hammer_t2',
    name: "Carpenter's Hammer",
    kind: 'tool',
    quality: 'common',
    sellValue: 25,
    buyValue: 125,
  },
  frame_saw_t3: {
    id: 'frame_saw_t3',
    name: 'Frame Saw',
    kind: 'tool',
    quality: 'uncommon',
    sellValue: 60,
    buyValue: 300,
  },
  builder_level_t4: {
    id: 'builder_level_t4',
    name: "Builder's Level",
    kind: 'tool',
    quality: 'rare',
    sellValue: 150,
    buyValue: 750,
  },
  master_mallet_t5: {
    id: 'master_mallet_t5',
    name: "Master Builder's Mallet",
    kind: 'tool',
    quality: 'epic',
    sellValue: 400,
    buyValue: 2000,
  },

  // --- Blueprint scroll items (consumable, learned) ---
  blueprint_tent: {
    id: 'blueprint_tent',
    name: 'Blueprint: Tent',
    kind: 'quest',
    quality: 'common',
    sellValue: 1,
    noDiscard: true,
  },
  blueprint_wooden_shack: {
    id: 'blueprint_wooden_shack',
    name: 'Blueprint: Wooden Shack',
    kind: 'quest',
    quality: 'common',
    sellValue: 10,
    buyValue: 100,
    noDiscard: true,
  },
  blueprint_timber_cottage: {
    id: 'blueprint_timber_cottage',
    name: 'Blueprint: Timber Cottage',
    kind: 'quest',
    quality: 'uncommon',
    sellValue: 50,
    buyValue: 500,
    noDiscard: true,
  },
  blueprint_stone_house: {
    id: 'blueprint_stone_house',
    name: 'Blueprint: Stone House',
    kind: 'quest',
    quality: 'rare',
    sellValue: 200,
    buyValue: 2000,
    noDiscard: true,
  },
  blueprint_manor: {
    id: 'blueprint_manor',
    name: 'Blueprint: Country Manor',
    kind: 'quest',
    quality: 'epic',
    sellValue: 800,
    buyValue: 8000,
    noDiscard: true,
  },
  blueprint_grand_estate: {
    id: 'blueprint_grand_estate',
    name: 'Blueprint: Grand Estate',
    kind: 'quest',
    quality: 'legendary',
    sellValue: 2500,
    buyValue: 25000,
    noDiscard: true,
  },
};
